[project]
name = "hexhelp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chainlit>=2.9.6",
    "langchain>=1.2.10",
]
